## QQ邮箱配置
spring:
  mail:
    host: smtp.qq.com             # 发送邮件服务器
    username: 2768523766@qq.com    # 发送邮件的邮箱地址
    password: hlztenbtvuwsdfjh    # 客户端授权码，不是邮箱密码
    smtp.port: 465                # 端口号465或587
    from: 2768523766@qq.com       # 发送邮件的地址和上面的username的邮箱地址保持一致

    ## 可以任意
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    default-encoding: utf-8
